sudo: false
language: python
cache: pip

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- "3.8-dev"
- pypy

before_install:
- pip install -U setuptools wheel

install:
- pip install .[dev,test]

script:
- green

after_script:
- codecov

notifications:
  email:
  - M3RLINK@gmx.de

deploy:
  provider: pypi
  user: "m3rlink"
  skip_existing: true
  distributions: "sdist bdist_wheel"
  password:
    secure: 0SkvBffT2oqOHOwzDl1OLOjNFjahmpS/Lwe3qisTqRGA5jpKbip3dWCI9CuCZT2lYULurdVF15T0XNMn/Y9f2/rJk09jOomV1yUG+2AzqSy+zljgzWtrzaj2YcZMsvNqmfv5EQphttevcrh2a783Uz5UBvdMohMea0VqM3QOafMPLiIPUPsjP2WJyTOzlFcmpRxMab6hf84Y9KBDoK1y+FXKlje60+SJwYr46od5jUnezbZS0a9jMkfLICRSADRDeWwgDP7LJitMMDeDNd9OdlXeN2NiWVjv16Vjv3HV0cSaP+EkbivVhLpGvz8fNORD8PW4jQt/vMm+l68weyN7FYPXrlaa/hFsH+zekYCVX880aN2Y3Flzxv9xFKbM7Hq/N0hlCS4fdQEabF3zSdnCtLih/nFTx+HXU0h0zSqa1miRA2fnT6SylNIvCGudRdvytr0s5Zr5+MqLilqKLcEeSbnn4jv3/RgQfAN3HkOTyGWX3FlZsAVI61skO56g8rt/wupr45KQoSTO/+lLwScmgLag2/5E4RpjbMT5AvPuJmsKh9PY4yuhjSnzHJHBCtthyEomyjGm0YObuc3lXHkiUiDpJ/CExtTGiZHMUeL4wiGh0gXxrtVHPqHDbnStRqrC7D96aKt9LS2GZizme8f33kFR4JLAVN8cqy1Yi/Lp9Lw=
